[[main]]
  name = "爱"
  pageRef = "docs"
  weight = 10

[[main]]
  name = "诗"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "归"
  pageRef = "archive"
  weight = 30

[[main]]
  name = "情"
  weight = 40

[[main]]
  name = "忆"
  pageRef = "goods"
  weight = 50