[[main]]
  name = "Love"
  pageRef = "docs"
  weight = 10

[[main]]
  name = "Poem"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "Sum"
  pageRef = "archive"
  weight = 30


[[main]]
  name = "Movement"
  pageRef = "goods"
  weight = 50