baseURL = "https://loveat20201001.cn"

hasCJKLanguage = true
defaultContentLanguage = "zh-hans"

[pagination]
pagerSize = 18

enableGitInfo = true
enableEmoji = true
      
[mediaTypes.'application/x-ndjson']
  suffixes = ["ndjson"]

[outputs]
  home = ["HTML", "Algolia"]

[outputFormats]
  [outputFormats.Algolia]
    baseName = "algolia"
    isPlainText = true
    notAlternative = true
    mediaType = "application/x-ndjson"

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = false

  [markup.tableOfContents]
    endLevel = 3
    startLevel = 2
